// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byocyavrqkgvxxnqnqud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5b2N5YXZycWtndnh4bnFucXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MzI2NTgsImV4cCI6MjA3MDQwODY1OH0.jyw09S6yERyQiVn7RmrgsS_0zMSSKP5JXaSErI9cfD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});